version: '2.1'
jobs:
  a:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-8
        command: |-
          echo adoptopenjdk-8
          docker build -t computesoftware/adoptopenjdk-8:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8:$CIRCLE_SHA1
  b:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-8-intel-mkl-2018.4-057
        command: |-
          echo adoptopenjdk-8-intel-mkl-2018.4-057
          docker build -t computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057:$CIRCLE_SHA1
  c:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-8-tools-deps-1.10.1.466
        command: |-
          echo adoptopenjdk-8-tools-deps-1.10.1.466
          docker build -t computesoftware/adoptopenjdk-8-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-tools-deps-1.10.1.466:$CIRCLE_SHA1
  d:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          echo adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466
          docker build -t computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
  e:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-11
        command: |-
          echo adoptopenjdk-11
          docker build -t computesoftware/adoptopenjdk-11:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11:$CIRCLE_SHA1
  f:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-11-intel-mkl-2018.4-057
        command: |-
          echo adoptopenjdk-11-intel-mkl-2018.4-057
          docker build -t computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057:$CIRCLE_SHA1
  g:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-11-tools-deps-1.10.1.466
        command: |-
          echo adoptopenjdk-11-tools-deps-1.10.1.466
          docker build -t computesoftware/adoptopenjdk-11-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-tools-deps-1.10.1.466:$CIRCLE_SHA1
  h:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build & push adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          echo adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466
          docker build -t computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
workflows:
  version: '2'
  ci-workflow:
    jobs:
    - a: {context: docker-env}
    - b: {context: docker-env}
    - c: {context: docker-env}
    - d: {context: docker-env}
    - e: {context: docker-env}
    - f: {context: docker-env}
    - g: {context: docker-env}
    - h: {context: docker-env}
