version: '2.1'
jobs:
  publish-adoptopenjdk-8-alpine:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-alpine
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-alpine:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-alpine.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-alpine:$CIRCLE_SHA1
  publish-adoptopenjdk-11-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-11-alpine-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-alpine-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-alpine-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-alpine-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-alpine-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-8-alpine-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-alpine-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-alpine-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-alpine-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-alpine-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-11-alpine-intel-mkl-2018.4-057:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-alpine-intel-mkl-2018.4-057
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-alpine-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-alpine-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-alpine-intel-mkl-2018.4-057:$CIRCLE_SHA1
  publish-adoptopenjdk-8:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8
        command: |-
          docker build -t computesoftware/adoptopenjdk-8:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8:$CIRCLE_SHA1
  publish-adoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-8-alpine-intel-mkl-2018.4-057:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-alpine-intel-mkl-2018.4-057
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-alpine-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-alpine-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-alpine-intel-mkl-2018.4-057:$CIRCLE_SHA1
  publish-adoptopenjdk-11-intel-mkl-2018.4-057:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-intel-mkl-2018.4-057
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057:$CIRCLE_SHA1
  publish-adoptopenjdk-11:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11
        command: |-
          docker build -t computesoftware/adoptopenjdk-11:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11:$CIRCLE_SHA1
  publish-adoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-8-intel-mkl-2018.4-057:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-intel-mkl-2018.4-057
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-intel-mkl-2018.4-057.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057:$CIRCLE_SHA1
  publish-adoptopenjdk-11-alpine:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-alpine
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-alpine:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-alpine.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-alpine:$CIRCLE_SHA1
  publish-adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466:$CIRCLE_SHA1
  publish-adoptopenjdk-8-tools-deps-1.10.1.466:
    docker:
    - {image: 'docker:17.05.0-ce-git'}
    steps:
    - checkout
    - run:
        name: Build & pushadoptopenjdk-8-tools-deps-1.10.1.466
        command: |-
          docker build -t computesoftware/adoptopenjdk-8-tools-deps-1.10.1.466:$CIRCLE_SHA1 . --file dockerfiles/adoptopenjdk-8-tools-deps-1.10.1.466.Dockerfile
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push computesoftware/adoptopenjdk-8-tools-deps-1.10.1.466:$CIRCLE_SHA1
workflows:
  version: '2'
  ci-workflow:
    jobs:
    - publish-adoptopenjdk-8: {context: docker-env}
    - publish-adoptopenjdk-8-intel-mkl-2018.4-057: {context: docker-env}
    - publish-adoptopenjdk-8-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-8-intel-mkl-2018.4-057-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-8-alpine: {context: docker-env}
    - publish-adoptopenjdk-8-alpine-intel-mkl-2018.4-057: {context: docker-env}
    - publish-adoptopenjdk-8-alpine-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-8-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-11: {context: docker-env}
    - publish-adoptopenjdk-11-intel-mkl-2018.4-057: {context: docker-env}
    - publish-adoptopenjdk-11-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-11-intel-mkl-2018.4-057-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-11-alpine: {context: docker-env}
    - publish-adoptopenjdk-11-alpine-intel-mkl-2018.4-057: {context: docker-env}
    - publish-adoptopenjdk-11-alpine-tools-deps-1.10.1.466: {context: docker-env}
    - publish-adoptopenjdk-11-alpine-intel-mkl-2018.4-057-tools-deps-1.10.1.466: {context: docker-env}
